name: build QMK

on:
  - push

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/qmk/qmk_cli:latest

    steps:
    - name: Clone qmk/qmk_firmware
      uses: actions/checkout@v2
      with:
        repository: 'qmk/qmk_firmware'
        submodules: true

    - name: Setup QMK
      shell: bash
      run: qmk setup --home ./ --yes

    - name: Clone yusukemorita/keyball44_keymap
      uses: actions/checkout@v2
      with:
        path: './keyboards/'

    - name: test
      run: ls

    - name: test 2
      run: ls ./keyboards

    - name: Compile
      run: cd ./keyboards/keyball/keyball44/keymaps/develop && qmk compile

    - uses: actions/upload-artifact@v2
      with:
        name: keyball44.hex
        path: ./.build/keyball44.hex
