name: build QMK

on:
  - push

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/qmk/qmk_cli:latest

    steps:
    - name: Checkout yusukemorita/keyball44_keymap
      uses: actions/checkout@v4

    - name: Cache qmk repository
      id: cache-qmk-repository
      uses: actions/cache@v4
      with:
        path: __qmk__
        key: ${{ runner.os }}-qmk-repository

    - name: Checkout qmk/qmk_firmware
      uses: actions/checkout@v4
      with:
        path: __qmk__
        repository: qmk/qmk_firmware
        submodules: recursive
        ref: '0.22.14'

    - name: Setup QMK
      shell: bash
      run: qmk setup --home ./__qmk__ --yes

    - name: Install symbolic link
      run: ln -s $(pwd)/keyball __qmk__/keyboards/keyball

    - name: Compile
      run: qmk compile -kb keyball/keyball44 -km default -j 4

    - name: Upload built firmware to artifact
      uses: actions/upload-artifact@v4
      with:
        name: keyball44-firmware
        path: __qmk__/*.hex
